sudo: required
language: java
jdk: oraclejdk8
 
services:
- docker
 
env:
  global:
  - secure: "B8h0B2d0X2eJXyfbehymFyYxt5KvyQR85DHLGpEAiCTG9pbJm68JkL52biDjMS0O3rf/tv3TX2NdnB9FQ2SoV/POCtQbdx7YxSddgspXkhaSGkcNiBAlLr+Pp1fe3Vku5nqQmq9rGSRlkJcIFTo6fzmffvmMGgt7CjnAbO6Wyid3mNoZt+gCpctHY30oMZ2rK2rZLzGTPd//7/8qe+MRj++jnou614xYv5bE0qpYd2AyXrDSozk+PiHCOVlXxlWLYfQcyTnO5k7SBfGnvmB6Y5G84bg3xTnjUzMO+uWaYsgJ8D86avFbNjVd2VbFoHWtLo5lfz36csA+lt0G4uLj3AqnmYpplV6TSQB5f0ws1HvLembaB+BsNs/9IhJnanmyouT0vz+lZuIHA0FZz7bM684V6tLPvdggjFjUKjYmORSPCMWnkZMp7Sk7+R9ZoBWDH8eYN7HrN+epD26b55XVXE6Dt3KRlqxuYanfLEtpWJey5uNC8GUlTYR2v3MEyUXI/xzlIrg3lZ/+QCLBODCTuv4MzTmzMIuIqShIdYJ+zw/jN9Z2tFOutMneh4sTtk4eh2ZgqUPBfUOxjcmPtNXt7XAMFWPgqrBm+EgDIPxqrlP497Mu3IA8xioi2TxCPsuEsQOMqa9ab8XaosrxXxIA9uRFJcUbOhw3REkz3ZCETxY="
  - secure: "TdSkVGFjhjPsqJ4HrTFQ2Vh7OeNBtGL/H9rCrHv9TuJpkXpVJdnsPKj6sjssupRjbnoB9PGfo6M5tD6J+7tpTL0xBCxCOOsm7TYlOh7pHxU6rzQYz3hVnKQBtrKcJHqr/yHEP4UP1omi3Wz7h8U6aWqzjDO/wo8eZ01RNmsEp4aT62y9ZqfPFgT055rJjqHLbbtX3uyhbX1Ay7DFTy0Cf9P3QFIXh7fBD8/CqioDEGzKfHo9GHUgl2Lm+aOnQzE+JOt3S0abxAN86AZS2qmiRX8yI5bbNeG0k+gm++krsrAlG07TafI9yOp/wBdCgTBtshXtSvSdvFKzAyteIykH0NxkU6ytkZOZmH/cauXrgStVNQ3nOgJx3ABTOGJPi8zO+QtU46J+Bp684ISxU/9Dy5lU016M3NnsC0lnRRnSwGEV/4ii/5OqDAKUzq+zIAxC5h72sKJEc5L6v5NpJuM1tZZN+2aM2CW6jnuBti1QDfu12jicyB21rG4Rp7yIrCaaZFPdhwcqjbt2zrAgiKeMLeJwhPS4zRV0uIXVrGm7kwUizZtN7/i1nxR0tKePa7849g9D0D55WvtOMGomR7qg5G9iYaSwJCCFJBR3ZA1Ohypukm0+N3Aqm1Wf/QG/F8olhQsSOzhZsfIMsjcn+aUSiuxHEVHzxYzEliMKNv4bQiU="
  - secure: "Y69UFCzqqF1JrHjC3NM6l/zLyjgfGkq1KcUyFHMKHR5L5DjuLZTL4LnRcMYqffoBupPunanq+t3TQYqQfah7epWsCpuCuJrq83dKytLJ8/kx1MqO1/9FakJ7TjcfCHyV7hEIEkdb4ZkJUYeFKrqKLuTUVINXAqHjqKbovtMuCO7pi8H1eyS6uYOVvNXQPtwoLAgTkcy4UaXCwQ33ByEDk2lvcnSz7N3p9bdzX1ZlxRdLJFU+dY6bVmms5VjaAu+V/eY//W1U2D992hpamLxqUzkUQ4iuN43/e1V1ofEHmLSo9096Z6PfuGd47l1M6hF2heIIcx185EsjHrH4UOkMTJx0Vc7ilTxLr4bgNK2LnoiaPwz/xKTqgXa56aeH+80VEGLR9xiLtqH5S79c3MzfMpLdH1nYgtYDEpsQfgoJHmVJZdHsyR1DGBFtDG52KHyq7p9UsY/TrdtzWotRbw8R36drvEabFadC+M4EMRU0zE5Rx5X29nWkk+eeaMM7estL53m7HST4MpOvR+0gs2bJpYMWcryJjpplovThAfORr5P+LjAPITF7Qj5x/j4vNyeYmXg61m2JOHIOM/w1sgXPGPsnvC4yZVMC+NxnfAPkdkr775Oztuhbe2wTj6fjK5eoWM880kjX3VOLbSpcsqVz2oG4iAzH3jY4empCmTTQIrE="

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=nnthai1997/demo_travis_cicd
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: demo-travis-cicd
