sudo: required
language: java
jdk: oraclejdk8
 
services:
- docker
 
env:
  global:
  - secure: "B8h0B2d0X2eJXyfbehymFyYxt5KvyQR85DHLGpEAiCTG9pbJm68JkL52biDjMS0O3rf/tv3TX2NdnB9FQ2SoV/POCtQbdx7YxSddgspXkhaSGkcNiBAlLr+Pp1fe3Vku5nqQmq9rGSRlkJcIFTo6fzmffvmMGgt7CjnAbO6Wyid3mNoZt+gCpctHY30oMZ2rK2rZLzGTPd//7/8qe+MRj++jnou614xYv5bE0qpYd2AyXrDSozk+PiHCOVlXxlWLYfQcyTnO5k7SBfGnvmB6Y5G84bg3xTnjUzMO+uWaYsgJ8D86avFbNjVd2VbFoHWtLo5lfz36csA+lt0G4uLj3AqnmYpplV6TSQB5f0ws1HvLembaB+BsNs/9IhJnanmyouT0vz+lZuIHA0FZz7bM684V6tLPvdggjFjUKjYmORSPCMWnkZMp7Sk7+R9ZoBWDH8eYN7HrN+epD26b55XVXE6Dt3KRlqxuYanfLEtpWJey5uNC8GUlTYR2v3MEyUXI/xzlIrg3lZ/+QCLBODCTuv4MzTmzMIuIqShIdYJ+zw/jN9Z2tFOutMneh4sTtk4eh2ZgqUPBfUOxjcmPtNXt7XAMFWPgqrBm+EgDIPxqrlP497Mu3IA8xioi2TxCPsuEsQOMqa9ab8XaosrxXxIA9uRFJcUbOhw3REkz3ZCETxY="
